name: Code Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get install lcov gcovr

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -DENABLE_COVERAGE=ON ..
          make

      - name: Run Tests
        run: ./build/my_executable

      - name: Generate Coverage Report
        run: |
          cd build
          gcovr -r . --html --html-details -o coverage_report.html

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: build/coverage_report.html
